version: 2
jobs:
  build:
    docker:
      - image: peavers/docker-firebase-ember:latest
    steps:
      - checkout
      - run:
          name: Installing Libraries
          command: npm install

      - run:
          name: Deploy
          command: firebase deploy --only functions --token=$FIREBASE_DEPLOY_TOKEN