version: 2

defaults: &DEFAULT
  docker:
    - image: peavers/docker-firebase-ember:latest

jobs:
  build_environment:
    <<: *DEFAULT
    steps:
      - checkout
      - run:
          name: Installing Libraries
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - build_environment


